### ISSUE TITLE
Minor : Profile page display blank during non-log-in status

### ISSUE THREAD

**Issue by haonanzzz** [info442-su23/d-team#101]
- Profile page can display two interfaces as openning
- minor
- As I noticed, only when during the log in status, the profile page display users' profile information. 
- Microsoft edge on Win 11
- Before sign up and log in in the application, the profile page that redirected from clicking <profile> button display me a blank, which is confusing at first; after finishing the sign up and log in process, the profile page then show me contents
- Expected to see that the profile page displays something like 'you are not log in yet' or 'log in for profile information'
- Actual results being blank page

**Comment by FastFusion5** [comment]
Duplicate with #96
