### ISSUE TITLE
Page is not found when I refresh the website (bug major)

### ISSUE THREAD

**Issue by luckypanda88** [info442-su23/d-team#102]
- When I try to refresh on the Map and Create opportunity pages/tab, I get an error message that says Page Not found. 
- Environment it was encountered in Safari and Google Chrome
- Steps to reproduce: Be on the Map or Create opportunity tab. Click refresh button. Error should appear. After, I click "back to our site" link from the error message (it takes me back to the page). But, if I repeat the step a few more times, the "back to our site" link does not work anymore and I am stuck on the error message page. Make sure to check the other tabs on your website too!
- Expected result: To still be able to see and use the page that I refreshed
- Actual result: The error message I got was "Page Not Found Looks like you've followed a broken link or entered a URL that doesn't exist on this site..." - The back to our site link on the error message will not take me back to the website sometimes.

**Comment by taylor-russon** [comment]
I also am having this problem using Chrom Version 115.0.5790.170 on macOS Monterey Version 12.5. I found that every time I refresh the page it provides a "Page not found" message and it happens on all the pages except the home page. 

<img width="508" alt="Screen Shot 2023-08-08 at 6 07 01 PM" src="https://github.com/info442-su23/d-team/assets/91644521/ed7d2427-d08f-43fd-8455-0aa3da55075a">

**Comment by sjhu2020** [comment]
works in localhost but not netlify

**Comment by sjhu2020** [comment]
netlify issue, wont fix
