### ISSUE TITLE
Must fill out the middle name to submit the wavier form in profile page. (Enhancement)

### ISSUE THREAD

**Issue by MarinaCui** [info442-su23/d-team#104]
Summary: I must fill out the middle name to submit the wavier form in profile page, but I do not have a middle name.
Environment: Chrome 115.0.5790.170 on macOS Ventura 13.4
Steps to Reproduce:Profile -> Fill out all other blanks except middle name -> Submit 
Expected Result: Submitted my form
Actual Result: I need to fill all the blanks including the middle name.

**Comment by elisabeth-h7** [comment]
unable to reproduce
