### ISSUE TITLE
Volunteer Waiver Form Social Security Number (Minor Bug)

### ISSUE THREAD

**Issue by atimch** [info442-su23/d-team#106]
On the Volunteer Waiver Form no input is possible to type but it can be filled in with a paste. There is also no limit to the size. Tested by pasting in the group url. Have to right click to paste cant ctr-v.

Expected can type, actual; cannot type in field.

Firefox

**Comment by ericagordy** [comment]
I am on chrome and this part of the form does not work for me as well. I also think it is a poor design choice to ask volunteers for their socials. This is a very personal piece of information and I can not be sure that your site has the proper security to keep it safe.

**Comment by elisabeth-h7** [comment]
can't reproduce
