### ISSUE TITLE
Major bug: Unable to enter the social security No. for the waiver form in profile page

### ISSUE THREAD

**Issue by MarinaCui** [info442-su23/d-team#108]
Summary: Unable to enter the social security No. for the waiver form in profile page.
Environment: Chrome 115.0.5790.170 on macOS Ventura 13.4
Steps to Reproduce:Profile -> Fill out all blanks
Expected Result: Enter my SSN in the box
Actual Result: Not able to enter anything in the SSN box.

**Comment by elisabeth-h7** [comment]
unable to reproduce

**Comment by elisabeth-h7** [comment]
duplicate

**Comment by FastFusion5** [comment]
I tested with Chrome and it worked. SSN is a nine-digit number, and to prevent incorrect inputs, we disabled the letter and special character keys in the process.
