### ISSUE TITLE
create an account-major issue

### ISSUE THREAD

**Issue by Zuoooooo** [info442-su23/d-team#109]
When I create an account, the email address can be filled in arbitrarily. For example, the normal email format is xxxxx@gmail.com, but when I use this format xxxxx@gmail can also complete the registration.

Expectation: When using the wrong email format to register, a prompt message will appear asking to use the correct email format.

<img width="382" alt="Screen Shot 2023-08-08 at 5 44 47 PM" src="https://github.com/info442-su23/d-team/assets/114701960/2d9ee2ae-3ccc-4ac1-a97e-39993d1a313d">

**Comment by Zuoooooo** [comment]
<img width="339" alt="Screen Shot 2023-08-08 at 5 50 02 PM" src="https://github.com/info442-su23/d-team/assets/114701960/dd0ba98d-e94d-48c6-bdc5-1a65afec628d">

**Comment by Zuoooooo** [comment]
<img width="339" alt="Screen Shot 2023-08-08 at 5 50 02 PM" src="https://github.com/info442-su23/d-team/assets/114701960/dd0ba98d-e94d-48c6-bdc5-1a65afec628d">

**Comment by FastFusion5** [comment]
https://github.com/info442-su23/d-team/commit/d9c7e3b25b4c7a4d43ee1816ad3c14f67eb41e82
