### ISSUE TITLE
Major bug: Unable to log back to my created account.

### ISSUE THREAD

**Issue by MarinaCui** [info442-su23/d-team#111]
Summary: Unable to log back to my created account.
Environment: Chrome 115.0.5790.170 on macOS Ventura 13.4
Steps to Reproduce: Create account -> log out -> log in using the created account 
Expected Result: Successfully log in.
Actual Result: Error state saying Username/password is incorrect

**Comment by sjhu2020** [comment]
works on react but not netlify

**Comment by sjhu2020** [comment]
netlify issue, won't fix
