### ISSUE TITLE
Minor bug: Phone number and Address are auto completed 

### ISSUE THREAD

**Issue by ericagordy** [info442-su23/d-team#112]
When I create my profile the address and phone number are auto completed before I have even entered my own information. 
They should be blank at the start of the profile creation, otherwise many users will have the same number and address in the data base if they do not choose to alter it themselves. 
<img width="619" alt="Screenshot 2023-08-08 at 5 51 15 PM" src="https://github.com/info442-su23/d-team/assets/66372667/b5a9fd33-ef0b-441b-98f7-ad127982d332">

**Comment by elisabeth-h7** [comment]
- stretch requirement
