### ISSUE TITLE
Major bug: Unable to mark complete for the wavier form in profile page.

### ISSUE THREAD

**Issue by MarinaCui** [info442-su23/d-team#113]
Summary: Unable to mark complete for the wavier form in profile page.
Environment: Chrome 115.0.5790.170 on macOS Ventura 13.4
Steps to Reproduce: Profile -> Mark complete
Expected Result: Marked
Actual Result: No reactions after clicking on the box.

**Comment by elisabeth-h7** [comment]
- stretch requirement

**Comment by elisabeth-h7** [comment]
works once waiver is actually completed
