### ISSUE TITLE
Minor bug: Profile page looks too empty when profile tab is clicked before signing up.

### ISSUE THREAD

**Issue by kchoi22** [info442-su23/d-team#114]
Summary:

When I clicked on the profile page before logging in I wasn't able to see anything get rendered on the page. 

Environment: MacOS Google Chrome

Steps to Reproduce: Opened the url, clicked on the profile tab.

Actual result: Blank profile page.

Expected result: Profile information.

**Comment by siyuanji1** [comment]
It would be better to provide users with instructions indicating that they need to log in to check their profile, or to automatically redirect them to the login page.

<img width="1438" alt="截屏2023-08-08 下午6 44 21" src="https://github.com/info442-su23/d-team/assets/114948473/eabddbb6-063b-4f21-8edb-4d5bf8b76f13">

**Comment by elisabeth-h7** [comment]
- stretch requirement

**Comment by elisabeth-h7** [comment]
duplicate

**Comment by FastFusion5** [comment]
https://github.com/info442-su23/d-team/commit/d9c7e3b25b4c7a4d43ee1816ad3c14f67eb41e82
