### ISSUE TITLE
Feature request: Change website logo

### ISSUE THREAD

**Issue by VictoriaVVei** [info442-su23/d-team#116]
Description of the requested feature: You can change the website logo through html file
Why: The logo right now is react logo.
Attachments: 
Your website: 
![0473bc281beb37e8e28660a03766023](https://github.com/info442-su23/d-team/assets/91993339/b3373945-0de5-4a15-acd5-be9515a1a8ff)

**Comment by elisabeth-h7** [comment]
duplicate
