### ISSUE TITLE
Cannot Edit Profile - Minor Bug

### ISSUE THREAD

**Issue by taylor-russon** [info442-su23/d-team#117]
I am using Chrome Version 115.0.5790.170 on macOS Monterey Version 12.5
When I try to edit my profile on the Profile tab, nothing happens. I expected it to let my change things like my username, password, email, or phone number, but the "edit profile" text is not clickable.

<img width="393" alt="Screen Shot 2023-08-08 at 6 28 04 PM" src="https://github.com/info442-su23/d-team/assets/91644521/93186a53-4b81-4122-afba-e459558e2abd">

**Comment by elisabeth-h7** [comment]
stretch requirement
