### ISSUE TITLE
Minor Bug: The map doesn't fit the body of the website

### ISSUE THREAD

**Issue by ryo884-2177391** [info442-su23/d-team#118]
<img width="1440" alt="Screenshot 2023-08-08 at 6 29 03 PM" src="https://github.com/info442-su23/d-team/assets/92127242/f213dcbd-00d4-45e9-a06c-0323a7de7747">
I really like the concept of the website! One thing that I can mention is that the map doesn't fit the body content (I attached the screenshot here, so hopefully, you can check them out!). Also, the NavBar doesn't fit the desktop screen as well, so you will need to edit the styling parts in map.js, and apply the fittable size to the google map. Or, you will be able to attach the className to it in map.js, import App.css, and apply some methods to the map.js from App.css. Overall, you guys did good job!

**Comment by elisabeth-h7** [comment]
- need to add map to separate styled file that has already been created 
- fix media query for nav bar
