### ISSUE TITLE
Wording on the homepage starts to come off screen a bit- minor

### ISSUE THREAD

**Issue by Ghermo35** [info442-su23/d-team#119]
![65ACAD13-23A6-46FC-91DA-FD1F37B86184](https://github.com/info442-su23/d-team/assets/43656152/134a903a-965d-47f7-b2f1-c1a903528855)

the S In homelessness is at the very edge of the screen on a mobile device. Minor issues once fixed other than that app is functional well and looks great.

**Comment by elisabeth-h7** [comment]
- need to add media queries for nav bar and first header in home page
