### ISSUE TITLE
major -- able to create multiple accounts with exact same username and email

### ISSUE THREAD

**Issue by EloraHob** [info442-su23/d-team#122]
I am unable to login after logging out with same credentials, but am able to create a new account with the same username, password, and email. 

When creating a new account from the homepage, the profile page displays after submitting info, but URL is still "https://teamdignity.netlify.app/HomePage". Refreshing the page from this screen brings up an error.

![Screenshot 2023-08-10 at 3 38 33 PM](https://github.com/info442-su23/d-team/assets/104376570/af8282c5-ab34-4542-9c97-6686bca2d03c)

**Comment by elisabeth-h7** [comment]
similar to issue #111 , except for being able to log in with same username/password

**Comment by FastFusion5** [comment]
https://github.com/info442-su23/d-team/commit/d9c7e3b25b4c7a4d43ee1816ad3c14f67eb41e82
