### ISSUE TITLE
Profile page isnt rendering (Major Bug)

### ISSUE THREAD

**Issue by Mustafabd** [info442-su23/d-team#96]
- When I go to the profile page I just see a blank white screen 
- I am using Microsoft Edge
- Make sure that the page correctly renders
- I Was expecting to see a profile page, but instead I saw a blank white page
- 
<img width="1112" alt="image" src="https://github.com/info442-su23/d-team/assets/80429899/6c141f8f-e84e-4fd3-ac05-b0065804feb6">

**Comment by siyuanji1** [comment]
After I signed up for a user account and tried to visit the page again, I found my personal information displayed there. However, the site did not allow me to modify the information, and I suspect that these details were generated automatically.

<img width="1155" alt="截屏2023-08-08 下午5 39 02" src="https://github.com/info442-su23/d-team/assets/114948473/8c6405ff-f782-439c-b38c-0f02afd5d95c">

**Comment by FastFusion5** [comment]
Profile page is naturally empty when user is not logged in/haven't created an account, but some kind of message prompting the user to login/create an account would be useful when the page is blank. Phone numbers and addresses are currently unchangeable.

**Comment by FastFusion5** [comment]
https://github.com/info442-su23/d-team/commit/d9c7e3b25b4c7a4d43ee1816ad3c14f67eb41e82
