### ISSUE TITLE
Major Bug: Log-in won't except a random password

### ISSUE THREAD

**Issue by sloaneshea** [info442-su23/d-team#99]
1. Major Bug
2. Log-in won't take any form of input as password and username duo
3. Chrome Version 115.0.5790.114 (Official Build) (x86_64)
4. Navigate to log-in page, input a username and password, press login
5. home page
6. incorrect input
7. 
<img width="628" alt="image" src="https://github.com/info442-su23/d-team/assets/77075019/cbd26dae-5f50-4b72-8bc4-0ad9ab7c8bd3">

**Comment by FastFusion5** [comment]
You need to create an account before being able to log in, that's part of a security procedure that prevents people from logging in with a random username/password duo
